apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "c920e60b4f7244c30da49646a1e48f28cf1646dff36bbafc2720307c972393d7"
  NEXTAUTH_SECRET: "FuAlQy8l4+kt1/vd/3FCK7dlv9mOqWjemKORzl+Q4bo="
